services:
  traffic-normal:
    build: ./traffic
    command: ["run", "/scripts/scenarios/normal.js"]
    environment:
      - TARGET_HOST=nginx
      - TARGET_PORT=80
    depends_on:
      - nginx
    restart: unless-stopped

  traffic-attacks:
    build: ./traffic
    command: ["run", "/scripts/scenarios/attacks.js"]
    environment:
      - TARGET_HOST=nginx
      - TARGET_PORT=80
    depends_on:
      - nginx
    restart: unless-stopped

  traffic-iast:
    build: ./traffic
    command: ["run", "/scripts/scenarios/iast.js"]
    environment:
      - TARGET_HOST=nginx
      - TARGET_PORT=80
    depends_on:
      - nginx
    restart: unless-stopped
