server.port=8003
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/petshop}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:petshop}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:petshop123}
spring.thymeleaf.cache=false
logging.level.root=WARN
logging.level.org.apache.catalina=WARN
logging.level.org.springframework.web=WARN
server.tomcat.accesslog.enabled=false
